name: Concurrency
on: push
env:
    WORKFLOW: ${{ github.workflow }}
    BRANCH: ${{ github.ref }}
concurrency:
    group: "${WORKFLOW}-${BRANCH}"
    cancel-in-progress: true
jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - run: |
                sleep 120
                echo "${WORKFLOW}"
                echo "${BRANCH}"