name: Conditions
on: push
jobs:
    skip-or-run:
        runs-on: ubuntu-latest
        if: >-
          ${{github.actor=='yuki-mori-1101' &&
            contains(github.run_id,'1')}}
        steps:
            - run: |
                echo "${{github.run_id}}"
                echo "Hello"
    fail:
        runs-on: ubuntu-latest
        steps:
            - run: exit 1
            - if: ${{failure()}}
              run: echo "Hello"