name: Conditions
on: push
jobs:
    skip-or-run:
        runs-on: ubuntu-latest
        env:
            RUN_ID: ${GITHUB_RUN_ID}
        steps:
            - run: echo "Hello"
              if: ${{contains(RUN_ID,'1')}}
