name: Compare functions
on: push
jobs:
    compare:
        runs-on: ubuntu-latest
        steps:
            - run: printenv | grep '_FUNC'
              env:
                CONTAINS_FUNC: ${{contains('Hello','ell')}}
                STARTS_WITH_FUNC: ${{startsWith('Hello','He')}}
                ENDS_WITH_FUNC: ${{endsWith('Hello','lo')}}
                FORMAT_FUNC: ${{format('{0},{1}.','Hello','world!')}}
                JOIN_FUNC: ${{join(github.event.*.html_url,',')}}
