name: Add mask
on: push
jos:
    log:
        runs-on: ubuntu-latest
        env:
            PASSWORD: SuperSecretValue
        steps:
            - run: echo "::add-mask::${PASSWORD}"
            - run: echo "${PASSWORD}"