name: Test
on:
    pull_request:
        paths: ['go/**/*.go']
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pwd && ls -la
            - uses: actions/setup-go@v5
              with:
                go-version-file: go/.go-version
            - run: go test go/excellent/*.go